config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "articles#index"
  resources :articles do
    resources :comments
  end

  resources :users

  get "sign_up", to: "registrations#new"
  post "sign_up", to:  "registrations#create"

  delete "logout", to: "sessions#destroy"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"

  resources :events


  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    belongs_to :user
    
    validates :body, presence: true, length: { minimum: 5}
  end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :event
    belongs_to :user
  end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  after_create_commit {broadcast_append_to "comments"}
  after_destroy_commit {broadcast_remove_to "comments"}
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
   attribute :user
end 

app/models/event.rb
class Event < ApplicationRecord
    has_many :bookings
    has_many :users, through: :bookings
end

app/models/events_join.rb
class EventsJoin < ActiveRecord::Base
    belongs_to :event
    belongs_to :user
end 

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    mount_uploader :photo, PhotoUploader

    has_many :events_join
has_many :events, through: :events_join
    validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     before_action :set_current_user

     def set_current_user
        if session[:user_id]
           Current.user = User.find_by(id: session[:user_id])
        end
     end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user
  def index
    @articles = Article.all
  end
  def show
    @article = Article.find(params[:id])
  end
  
  def new
    @article = Article.new
  end
  def all_comments
    @post = Post.find(params[:id])
  end
  def create
    @article = Article.new(article_params)
    @article.user_id = session[:user_id]
    if @article.save
      redirect_to articles_path
    else
      redirect_to articles_path, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to articles_path
    else
      render :edit, status: :unprocessable_entity
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
     def article_params
       params.require(:article).permit(:title, :body)
     end
     def authenticate_user
       if !Current.user
          redirect_to login_path
       end
     end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.new(comment_params)
        @comment.user_id = session[:user_id]
        @comment.article_id = params[:article_id]
        @comment.save
        redirect_to articles_path
        # respond_to do |format|
        #   format.turbo_stream
        #   format.html{redirect_to article_path(@article)}
        #   format.js
        # end
    end
    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to articles_path,status: 303
    end
    private
    def comment_params
        params.require(:comment).permit(:body)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
      @events = Event.all
  end

  def new
      @event = Event.new
  end

  def create
     @event = Event.new(event_params)
     if @event.save!
        redirect_to events_path
     else
        render :new
     end
  end

 def show_user_events
    @events = Current.user.events
 end

  private
    def event_params
       params.require("event").permit(:name,:description,:start_date,:end_date,:picture_attributes => {})
    end
end

app/controllers/gif_controller.rb
class GifController < ApplicationController

    before_filter :authorize
  
    def cool
    end
  
    def free
    end
  
  end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :authenticate_user
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
       session[:user_id] = @user.id
       redirect_to root_path
    else
        puts @user.errors.full_messages
        render :new, status: :unprocessable_entity
    end
  end
  
  private 
  def authenticate_user
    if Current.user
       redirect_to root_path
    end
  end
  def user_params
   params.require(:user).permit(:name,:password,:password_confirmation,:dob,:photo,:admin_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user , only: :new
  def new 
    @user = User.new
  end
  def create
    @user = User.find_by(name: params[:name])

    if @user.present? && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        flash[:user_id] = 'Successfully checked in'
        redirect_to root_path
    else
        render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path,status: :see_other
  end

  private
  def authenticate_user
    if Current.user
       redirect_to '/'
    end
  end
  def login_params
    params.require(:user).permit(:name,:password,:password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_Admin, only: [:index]
  before_action :is_AdminOrCurrentUser, except: [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to '/users/'
    else
       render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, status: :see_other
  end

  private
    def is_Admin
       if !(session[:user_id] and Current.user.admin_user)
          redirect_to articles_path
       end
    end 

    def is_AdminOrCurrentUser
      if !((session[:user_id] and Current.user.admin_user) || (Current.user.id == params[:id].to_i))
         redirect_to articles_path
      end
    end

    def user_params
      params.require(:user).permit(:name,:dob,:photo,:password,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>  
    <div>
      <%= form.label :body,class: "form-label" %><br>
      <%= form.text_area :body,rows: 3,class: "form-control"%><br>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit class: "btn btn-primary"%>
    </div>
  <% end %>


  

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
.collapsible {
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
}

.content {
  padding: 0 18px;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
  background-color: #f1f1f1;
}
.newpost{
  margin-left: 15%;
  width:800px;
  margin-bottom: 5%;
  margin-top: 5%;
}
.post{
  margin-bottom: 5%;
}
.ccontainer{
 
  margin-top: 10px;
}
.submittag{margin-left:40%; color:blue}
</style>
</head>
<body>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet"/>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

<div class="newpost">
<%= form_with scope: :article, url: articles_path , local:true do |form| %>

  <div>
    <%= form.text_area :body,rows: 10,class: "form-control"%><br>
  </div>

  <div class="submittag">
    <%= form.submit "Create Post" %>
  </div>
<% end %>


</div>
<% @articles.each do |article| %>
  <div class="post">
  <section style="background-color: #eee;">
    <div class="container my-5 py-5">
      <div class="row d-flex justify-content-center">
        <div class="col-md-12 col-lg-10 col-xl-8">
          <div class="card">
            <div class="card-body">
              <div class="d-flex flex-start align-items-center">
             
              <%= image_tag "profile.png" , :style => "height: 50px;" %>
               
                <div>
                  <h6 class="fw-bold text-primary mb-1"><%= article.user.name %></h6>
                  <p class="text-muted small mb-0">
                    Shared publicly - <%= time_ago_in_words(article.updated_at)%> ago
                  </p>
                </div>
              </div>
              <p style="font-size:30px"class="mt-3 mb-4 pb-2">
                <%= article.body%>
              </p>
              <% if Current.user.id ==article.user_id %>
              <div class="small d-flex justify-content-start">
                <a href="/articles/<%= article.id %>/edit" class="d-flex align-items-center me-3">
                  <i class="far fa-edit me-2"></i>
                  <p class="mb-0">Edit Post</p>
                </a>
                <%= link_to  article_path(article), class: "d-flex align-items-center me-3",data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } do %>
                  <i class="far fa-trash-alt me-2"></i>
                  <p class="mb-0">Delete Post</p>
                <% end %>
              </div>
              <% end %>
              <div class="ccontainer">
  <button class="collapsible">Show Comments</button>
  <div class="content">
  <%= render article.comments %> 
  <h2>Add a comment:</h2>
  <div id="new_comment">
  <%= form_with model: [ article, article.comments.build ] do |form| %>
      <p>
        <%= form.text_area :body %>
      </p>
      <p>
        <%= form.submit %>
      </p>
    <% end %>
    </div>
</div>

  
   
  </div>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
  
<% end %> 
<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.maxHeight){
      content.style.maxHeight = null;
    } else {
      content.style.maxHeight = content.scrollHeight + "px";
    } 
  });
}
</script>

</body>
</html>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/_comment.html.erb
<p>
 <% if comment.user.photo.present? %>
  <%=image_tag comment.user.photo_url(:thumb)%>
<% else %>
  <%= image_tag "profile.png" , :style => "height: 20px;" %>
<% end %>
  <%= comment.user.name %><br>
 <div >
  <%= comment.body %><br>
  <% if Current.user.id == comment.user_id %>
  <%= link_to "Delete Comment", [comment.article, comment], data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } , :style => "font-size: 12px;" %>
  <% end %>
</p>

app/views/comments/_form.html.erb
<div id="new_comment">
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
      <%= form.label :body%><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  </div>
  

app/views/event/index.html.erb
<h1>Events</h1>

<% @events.each do |event| %>
   <p><%= event.name %></p>
   <p><%= event.description %></p>
   <p><%= event.start_date %></p>
   <p><%= event.end_date %></p>
   
   <%= form_with url: "/book" do |form| %>
    <%= hidden_field_tag 'event_id', event.id %>
     <%= form.submit "Register" %>
   <% end %>
   <hr>
<% end %>

<%= link_to "New Event", new_event_path %>

app/views/events/_form.html.erb
<%= form_with model: event do |form| %>
  <div class="mb-3">
    <%= form.label :name ,class: "form-label" %>
    <%= form.text_field :name,class: "form-control"%>
   
  </div>

  <div class="mb-3">
    <%= form.label :description,class: "form-label" %>
    <%= form.text_area :description,rows: 3,class: "form-control"%>
    
  </div>

  <div class="mb-3">
     <%= form.label :start_date, class: "form-label" %><br>
     <%= form.date_field :start_date, class: "form-control" %>
  </div>

  <div class="mb-3">
     <%= form.label :end_date, class: "form-label" %><br>
     <%= form.date_field :end_date, class: "form-control" %>
  </div>

  <div class="mb-3">
  <label class="form-label">Profile photo</label>
  <%=form.fields_for :picture_attributes do |picture_f|%>
    <%= picture_f.file_field :name, class: "form-control" %>
 <%end%>
 </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/index.html.erb
<h1>Events</h1>

<% @events.each do |event| %>
   <% if event.picture && event.picture.name.present? %>
      <%= image_tag event.picture.name_url(:thumb) %>
   <% end %>
   <p><%= event.name %></p>
   <p><%= event.description %></p>
   <p><%= event.start_date %></p>
   <p><%= event.end_date %></p>
   
   <%= form_with url: "/book" do |form| %>
    <%= hidden_field_tag 'event_id', event.id %>
     <%= form.submit "Register" %>
   <% end %>
   <hr>
<% end %>

<%= link_to "New Event", new_event_path if Current.user.admin_user%>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render "form", event: @event %>

app/views/events/show_user_events.html.erb
<h1>My Events</h1>

<% @events.each do |event| %>
    <% if event.picture && event.picture.name.present? %>
       <%= image_tag event.picture.name_url(:thumb) %>
    <% end %>
    <p><%= event.name %></p>
    <p><%= event.description %></p>
    <p><%= event.start_date %></p>
    <p><%= event.end_date %></p>
    <hr>
 <% end %>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag "overall", "data-turbo-track": "reload" %>
 
  </head>

<h1>Edit User</h1>
<%= form_with model: Current.user do |form| %>
 <label>Name: </label>
 <p><%= form.text_field :name %></p>
 <label>Date of birth:</label>
 <p><%= form.date_field :dob %></p>
 <label>Photo:</label>
<p><%= form.file_field :photo %></p>
<p><%= form.submit "Submit" %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<!-- <% @users.each do |user| %>
   <p>
     <%= user.name %>
     <%= link_to "Show User", user %>
   </p>
<% end %> -->

<table class="table">
  <thead>
    <tr>
      <th scope="col">Sno.</th>
      <th scope="col">Users</th>
      <th scope="col">Profile Details</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each_with_index do |user,index| %>
    <tr>
      <th scope="row"><%= index+1 %></th>
      <td><%= user.name %></td>
<td>

 Date of birth: <%= user.dob %><br>
 Admin user : <%=user.admin_user %><br>
Image: 
 <% if user.photo.present? %>
<%= image_tag @user.photo_url(:thumb) if @user.photo.present? %>
<% else %>
<%= image_tag "profile.png" , :style => "height: 20px;" %>
<% end %>

</td>
<td>
<%= link_to "Edit Profile", edit_user_path(user) %><br>
<% if Current.user.id!=user.id%>
<%= link_to "Delete Profile", user_path(user), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
} %>
<% end %><br>
</td>
    </tr>
 <% end %> 
  </tbody>
 
</table>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>